// SPDX-FileCopyrightText: 2026 Mohd Umeer
// SPDX-License-Identifier: BSD-2-Clause

/* AUTO-GENERATED by tools/gen_c_structs.py -- do not edit. */
#ifndef BS_STRUCTS_H
#define BS_STRUCTS_H

#include <stdint.h>
#include <stddef.h>

#ifndef __cplusplus
#define kMaxPalettePredictorSize 128
#define kScalingListMatrixIds 6
#define kScalingListMaxCoefficients 64
#define kScalingListSizeIds 4
#else
#include <cstddef>
inline constexpr std::size_t kMaxPalettePredictorSize = 128;
inline constexpr std::size_t kScalingListMatrixIds = 6;
inline constexpr std::size_t kScalingListMaxCoefficients = 64;
inline constexpr std::size_t kScalingListSizeIds = 4;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct BsAv1ColorConfig;
struct BsAv1DecoderModelInfo;
struct BsAv1FilmGrainParams;
struct BsAv1FrameHeader;
struct BsAv1TimingInfo;
struct BsAvcHrdParameters;
struct BsAvcMmcoOperation;
struct BsAvcParsedSei;
struct BsAvcPredWeightTable;
struct BsAvcRefPicListModification;
struct BsAvcRefPicReorderingOp;
struct BsAvcScalingList;
struct BsAvcSeiMessage;
struct BsAvcSliceGroupMap;
struct BsAvcSliceHeader;
struct BsAvcVuiParameters;
struct BsHevcAlternativeTransferCharacteristics;
struct BsHevcAmbientViewingEnvironment;
struct BsHevcAspectRatio;
struct BsHevcBitDepth;
struct BsHevcChromaLocationInfo;
struct BsHevcCodingBlockGeometry;
struct BsHevcColourDescription;
struct BsHevcContentLightLevelInfo;
struct BsHevcCpbEntry;
struct BsHevcDerivedShortTermRefPicSet;
struct BsHevcDerivedShortTermReference;
struct BsHevcDisplayDimensions;
struct BsHevcFramePackingArrangement;
struct BsHevcHrdTimingInfo;
struct BsHevcInterRpsPrediction;
struct BsHevcInterRpsPredictionEntry;
struct BsHevcLevel;
struct BsHevcMasteringDisplayColourVolumeChromaticity;
struct BsHevcPictureStructure;
struct BsHevcPocConfiguration;
struct BsHevcPps3dExtension;
struct BsHevcPps3dExtensionDepthLayerTransform;
struct BsHevcPpsColourMappingOctant;
struct BsHevcPpsDeblockingFilter;
struct BsHevcPpsExtension;
struct BsHevcPpsMultilayerExtension;
struct BsHevcPpsRangeExtension;
struct BsHevcPpsRefLocationOffset;
struct BsHevcPpsSccExtension;
struct BsHevcPpsTileConfiguration;
struct BsHevcPredictionWeight;
struct BsHevcPredictionWeightTable;
struct BsHevcProfileTierLevelId;
struct BsHevcProfileTierLevelSubLayer;
struct BsHevcRecoveryPoint;
struct BsHevcRefPicListModification;
struct BsHevcRefPicListModificationData;
struct BsHevcReferencePictureSetInfo;
struct BsHevcSampleAspectRatio;
struct BsHevcSampleAspectRatioTableEntry;
struct BsHevcScalingListMatrix;
struct BsHevcSeiExtendedValue;
struct BsHevcSeiMessageHeader;
struct BsHevcShortTermNegativePicture;
struct BsHevcShortTermPositivePicture;
struct BsHevcShortTermRefPicSet;
struct BsHevcSliceDeblockingFilter;
struct BsHevcSliceEntryPointOffsets;
struct BsHevcSliceHeaderExtension;
struct BsHevcSliceLongTermReference;
struct BsHevcSliceReferencePictureInfo;
struct BsHevcSliceSegmentAddress;
struct BsHevcSliceSegmentHeader;
struct BsHevcSps3dViewExtension;
struct BsHevcSpsCodingBlockParameters;
struct BsHevcSpsExtension;
struct BsHevcSpsGeometry;
struct BsHevcSpsLongTermReferencePictures;
struct BsHevcSpsMultilayerExtension;
struct BsHevcSpsPcmParameters;
struct BsHevcSpsRangeExtension;
struct BsHevcSpsReferencePictureSetParameters;
struct BsHevcSpsSccExtension;
struct BsHevcSubLayerHrdParameters;
struct BsHevcSubLayerOrderingInfo;
struct BsHevcTemporalLayer;
struct BsHevcTimingInfo;
struct BsHevcVideoSignalType;
struct BsHevcVpsExtension;
struct BsHevcVpsLayerSet;
struct BsHevcVpsTimingInfo;
struct BsHevcWindow;
struct BsVp8FrameHeader;
struct BsVp9FrameHeader;
struct BsVvcDci;
struct BsVvcOpi;
struct BsVvcPictureHeaderRefPicListsEntry;
struct BsVvcPictureHeaderRefPicListsList;
struct BsVvcPictureParameterSet;
struct BsVvcSequenceParameterSet;
struct BsVvcSequenceParameterSetRefPicListEntry;
struct BsVvcSequenceParameterSetRefPicListStruct;
struct BsVvcVideoParameterSet;
struct BsAv1SequenceHeader;
struct BsAvcPictureParameterSet;
struct BsAvcSequenceParameterSet;
struct BsHevcHrdCommonInfo;
struct BsHevcHrdSubLayer;
struct BsHevcMasteringDisplayColourVolume;
struct BsHevcPictureDimensions;
struct BsHevcProfileTierLevel;
struct BsHevcScalingListData;
struct BsHevcSps3dExtension;
struct BsHevcVideoParameterSet;
struct BsVvcPictureHeaderRefPicLists;
struct BsHevcHrdParameters;
struct BsHevcPpsScalingListConfiguration;
struct BsHevcVpsHrdParameter;
struct BsHevcVuiParameters;
struct BsVvcPictureHeader;
struct BsVvcSliceHeader;
struct BsHevcPictureParameterSet;
struct BsHevcSequenceParameterSet;

typedef struct BsAv1ColorConfig {
    uint8_t high_bitdepth;
    uint8_t twelve_bit;
    uint8_t mono_chrome;
    uint8_t color_description_present_flag;
    uint8_t color_primaries;
    uint8_t transfer_characteristics;
    uint8_t matrix_coefficients;
    uint8_t color_range;
    uint8_t subsampling_x;
    uint8_t subsampling_y;
    uint8_t chroma_sample_position;
    uint8_t separate_uv_delta_q;
} BsAv1ColorConfig;

typedef struct BsAv1DecoderModelInfo {
    uint8_t buffer_delay_length_minus_1;
    uint32_t num_units_in_decoding_tick;
    uint8_t buffer_removal_time_length_minus_1;
    uint8_t frame_presentation_time_length_minus_1;
} BsAv1DecoderModelInfo;

typedef struct BsAv1FilmGrainParams {
    uint8_t apply_grain;
    uint16_t grain_seed;
    uint8_t update_grain;
    uint8_t film_grain_params_ref_idx;
    uint8_t num_y_points;
    uint8_t point_y_value[14];
    uint8_t point_y_scaling[14];
    uint8_t chroma_scaling_from_luma;
    uint8_t num_cb_points;
    uint8_t point_cb_value[10];
    uint8_t point_cb_scaling[10];
    uint8_t num_cr_points;
    uint8_t point_cr_value[10];
    uint8_t point_cr_scaling[10];
    uint8_t grain_scaling_minus_8;
    uint8_t ar_coeff_lag;
    uint8_t ar_coeffs_y_plus_128[24];
    uint8_t ar_coeffs_cb_plus_128[25];
    uint8_t ar_coeffs_cr_plus_128[25];
    uint8_t ar_coeff_shift_minus_6;
    uint8_t grain_scale_shift;
    uint8_t cb_mult;
    uint8_t cb_luma_mult;
    uint16_t cb_offset;
    uint8_t cr_mult;
    uint8_t cr_luma_mult;
    uint16_t cr_offset;
    uint8_t overlap_flag;
    uint8_t clip_to_restricted_range;
} BsAv1FilmGrainParams;

typedef struct BsAv1FrameHeader {
    int frame_type;
    uint8_t show_frame;
    uint8_t show_existing_frame;
    uint8_t frame_to_show_map_idx;
    uint32_t frame_presentation_time;
    uint32_t display_frame_id;
    uint8_t showable_frame;
    uint8_t error_resilient_mode;
    uint8_t disable_cdf_update;
    uint8_t allow_screen_content_tools;
    uint8_t force_integer_mv;
    uint32_t current_frame_id;
    uint8_t frame_size_override_flag;
    uint32_t order_hint;
    int32_t presentation_order;
    uint8_t buffer_removal_time_present_flag;
    uint32_t buffer_removal_time[32];
    uint8_t primary_ref_frame;
    uint16_t frame_width;
    uint16_t frame_height;
    uint16_t frame_width_minus_1;
    uint16_t frame_height_minus_1;
    uint8_t use_superres;
    uint8_t coded_denom;
    uint8_t superres_denom;
    uint16_t upscaled_width;
    uint8_t render_and_frame_size_different;
    uint16_t render_width;
    uint16_t render_height;
    uint16_t render_width_minus_1;
    uint16_t render_height_minus_1;
    uint8_t found_ref[7];
    uint8_t refresh_frame_flags;
    uint8_t allow_intrabc;
    uint8_t ref_order_hint[8];
    uint8_t frame_refs_short_signaling;
    uint8_t last_frame_idx;
    uint8_t golden_frame_idx;
    int8_t ref_frame_idx[7];
    uint32_t delta_frame_id_minus1[7];
    uint8_t allow_high_precision_mv;
    uint8_t is_filter_switchable;
    uint8_t interpolation_filter;
    uint8_t is_motion_mode_switchable;
    uint8_t use_ref_frame_mvs;
    uint8_t disable_frame_end_update_cdf;
    uint8_t uniform_tile_spacing_flag;
    uint8_t tile_cols_log2;
    uint8_t tile_rows_log2;
    uint8_t tile_cols;
    uint8_t tile_rows;
    uint8_t tile_start_col_sb[64];
    uint8_t tile_start_row_sb[64];
    uint8_t width_in_sbs_minus_1[64];
    uint8_t height_in_sbs_minus_1[64];
    uint16_t context_update_tile_id;
    uint8_t tile_size_bytes_minus1;
    uint8_t base_q_idx;
    int8_t delta_q_y_dc;
    uint8_t diff_uv_delta;
    int8_t delta_q_u_dc;
    int8_t delta_q_u_ac;
    int8_t delta_q_v_dc;
    int8_t delta_q_v_ac;
    uint8_t using_qmatrix;
    uint8_t qm_y;
    uint8_t qm_u;
    uint8_t qm_v;
    uint8_t segmentation_enabled;
    uint8_t segmentation_update_map;
    uint8_t segmentation_temporal_update;
    uint8_t segmentation_update_data;
    uint8_t feature_enabled[8][8];
    int16_t feature_value[8][8];
    uint8_t delta_q_present;
    uint8_t delta_q_res;
    uint8_t delta_lf_present;
    uint8_t delta_lf_res;
    uint8_t delta_lf_multi;
    uint8_t loop_filter_level[4];
    uint8_t loop_filter_sharpness;
    uint8_t loop_filter_delta_enabled;
    uint8_t loop_filter_delta_update;
    uint8_t update_ref_delta[8];
    int8_t loop_filter_ref_deltas[8];
    uint8_t update_mode_delta[2];
    int8_t loop_filter_mode_deltas[2];
    uint8_t cdef_damping_minus_3;
    uint8_t cdef_bits;
    uint8_t cdef_y_pri_strength[8];
    uint8_t cdef_y_sec_strength[8];
    uint8_t cdef_uv_pri_strength[8];
    uint8_t cdef_uv_sec_strength[8];
    uint8_t lr_type[3];
    uint8_t lr_unit_shift;
    uint8_t lr_uv_shift;
    uint8_t tx_mode;
    uint8_t reference_select;
    uint8_t skip_mode_present;
    uint8_t allow_warped_motion;
    uint8_t reduced_tx_set;
    uint8_t is_global[8];
    uint8_t is_rot_zoom[8];
    uint8_t is_translation[8];
    uint32_t gm_params[8][6];
    struct BsAv1FilmGrainParams film_grain;
    uint8_t frame_is_intra;
} BsAv1FrameHeader;

typedef struct BsAv1TimingInfo {
    uint32_t num_units_in_display_tick;
    uint32_t time_scale;
    uint8_t equal_picture_interval;
    uint32_t num_ticks_per_picture_minus_1;
} BsAv1TimingInfo;

typedef struct BsAvcHrdParameters {
    uint8_t cpb_cnt_minus1;
    uint8_t bit_rate_scale;
    uint8_t cpb_size_scale;
    uint32_t bit_rate_value_minus1[32];
    uint32_t cpb_size_value_minus1[32];
    uint8_t cbr_flag[32];
    uint8_t initial_cpb_removal_delay_length_minus1;
    uint8_t cpb_removal_delay_length_minus1;
    uint8_t dpb_output_delay_length_minus1;
    uint8_t time_offset_length;
} BsAvcHrdParameters;

typedef struct BsAvcMmcoOperation {
    uint32_t memory_management_control_operation;
    uint32_t difference_of_pic_nums_minus1;
    uint32_t long_term_pic_num;
    uint32_t long_term_frame_idx;
    uint32_t max_long_term_frame_idx_plus1;
} BsAvcMmcoOperation;

typedef struct BsAvcParsedSei {
    uint32_t rbsp_storage_count;
    uint8_t* rbsp_storage;
    uint32_t messages_count;
    struct BsAvcSeiMessage* messages;
} BsAvcParsedSei;

typedef struct BsAvcPredWeightTable {
    uint32_t luma_log2_weight_denom;
    uint32_t chroma_log2_weight_denom;
    uint8_t luma_weight_l0_flag[32];
    int16_t luma_weight_l0[32];
    int16_t luma_offset_l0[32];
    uint8_t chroma_weight_l0_flag[32];
    int16_t chroma_weight_l0[32][2];
    int16_t chroma_offset_l0[32][2];
    uint8_t luma_weight_l1_flag[32];
    int16_t luma_weight_l1[32];
    int16_t luma_offset_l1[32];
    uint8_t chroma_weight_l1_flag[32];
    int16_t chroma_weight_l1[32][2];
    int16_t chroma_offset_l1[32][2];
} BsAvcPredWeightTable;

typedef struct BsAvcRefPicListModification {
    uint8_t modification_flag;
    uint32_t ops_count;
    struct BsAvcRefPicReorderingOp* ops;
} BsAvcRefPicListModification;

typedef struct BsAvcRefPicReorderingOp {
    uint32_t reordering_of_pic_nums_idc;
    uint32_t abs_diff_pic_num_minus1;
    uint32_t long_term_pic_num;
} BsAvcRefPicReorderingOp;

typedef struct BsAvcScalingList {
    uint8_t present_4x4[6];
    uint8_t list_4x4[6][16];
    uint8_t present_8x8[2];
    uint8_t list_8x8[2][64];
} BsAvcScalingList;

typedef struct BsAvcSeiMessage {
    uint32_t payload_type;
    uint32_t payload_size;
    const uint8_t* payload;
} BsAvcSeiMessage;

typedef struct BsAvcSliceGroupMap {
    uint8_t slice_group_map_type;
    uint32_t run_length_minus1[8];
    uint32_t top_left[8];
    uint32_t bottom_right[8];
    uint8_t slice_group_change_direction_flag;
    uint32_t slice_group_change_rate_minus1;
    uint32_t pic_size_in_map_units_minus1;
    uint32_t slice_group_id_count;
    uint8_t* slice_group_id;
} BsAvcSliceGroupMap;

typedef struct BsAvcSliceHeader {
    uint32_t first_mb_in_slice;
    int slice_type;
    uint8_t pic_parameter_set_id;
    uint32_t frame_num;
    uint8_t field_pic_flag;
    uint8_t bottom_field_flag;
    uint32_t idr_pic_id;
    uint32_t pic_order_cnt_lsb;
    int32_t delta_pic_order_cnt_bottom;
    int32_t delta_pic_order_cnt[2];
    uint32_t redundant_pic_cnt;
    uint8_t direct_spatial_mv_pred_flag;
    uint8_t num_ref_idx_active_override_flag;
    uint8_t num_ref_idx_l0_active_minus1;
    uint8_t num_ref_idx_l1_active_minus1;
    struct BsAvcRefPicListModification ref_pic_list_modification_l0;
    struct BsAvcRefPicListModification ref_pic_list_modification_l1;
    struct BsAvcPredWeightTable pred_weight_table;
    uint8_t no_output_of_prior_pics_flag;
    uint8_t long_term_reference_flag;
    uint8_t adaptive_ref_pic_marking_mode_flag;
    uint32_t mmco_operations_count;
    struct BsAvcMmcoOperation* mmco_operations;
    uint8_t cabac_init_idc;
    int32_t slice_qp_delta;
    uint8_t disable_deblocking_filter_idc;
    int32_t slice_alpha_c0_offset_div2;
    int32_t slice_beta_offset_div2;
    uint32_t slice_group_change_cycle;
    uint8_t sp_for_switch_flag;
    int32_t slice_qs_delta;
    int32_t derived_poc;
} BsAvcSliceHeader;

typedef struct BsAvcVuiParameters {
    uint8_t aspect_ratio_info_present_flag;
    uint8_t aspect_ratio_idc;
    uint16_t sar_width;
    uint16_t sar_height;
    uint8_t overscan_info_present_flag;
    uint8_t overscan_appropriate_flag;
    uint8_t video_signal_type_present_flag;
    uint8_t video_format;
    uint8_t video_full_range_flag;
    uint8_t colour_description_present_flag;
    uint8_t colour_primaries;
    uint8_t transfer_characteristics;
    uint8_t matrix_coefficients;
    uint8_t chroma_loc_info_present_flag;
    uint32_t chroma_sample_loc_type_top_field;
    uint32_t chroma_sample_loc_type_bottom_field;
    uint8_t timing_info_present_flag;
    uint32_t num_units_in_tick;
    uint32_t time_scale;
    uint8_t fixed_frame_rate_flag;
    uint8_t nal_hrd_parameters_present_flag;
    struct BsAvcHrdParameters nal_hrd;
    uint8_t vcl_hrd_parameters_present_flag;
    struct BsAvcHrdParameters vcl_hrd;
    uint8_t low_delay_hrd_flag;
    uint8_t bitstream_restriction_flag;
    uint8_t motion_vectors_over_pic_boundaries_flag;
    uint32_t max_bytes_per_pic_denom;
    uint32_t max_bits_per_mb_denom;
    uint32_t log2_max_mv_length_horizontal;
    uint32_t log2_max_mv_length_vertical;
    uint32_t max_num_reorder_frames;
    uint32_t max_dec_frame_buffering;
} BsAvcVuiParameters;

typedef struct BsHevcAlternativeTransferCharacteristics {
    uint8_t preferred_transfer_characteristics;
} BsHevcAlternativeTransferCharacteristics;

typedef struct BsHevcAmbientViewingEnvironment {
    uint32_t ambient_illuminance;
    uint16_t ambient_light_x;
    uint16_t ambient_light_y;
} BsHevcAmbientViewingEnvironment;

typedef struct BsHevcAspectRatio {
    uint8_t present;
    uint8_t aspect_ratio_idc;
    uint16_t sar_width;
    uint16_t sar_height;
} BsHevcAspectRatio;

typedef struct BsHevcBitDepth {
    uint8_t luma;
    uint8_t chroma;
} BsHevcBitDepth;

typedef struct BsHevcChromaLocationInfo {
    uint8_t present;
    uint32_t chroma_sample_loc_type_top_field;
    uint32_t chroma_sample_loc_type_bottom_field;
} BsHevcChromaLocationInfo;

typedef struct BsHevcCodingBlockGeometry {
    uint32_t min_cb_size;
    uint32_t max_cb_size;
    uint32_t min_tb_size;
    uint32_t max_tb_size;
    uint8_t max_transform_hierarchy_depth_inter;
    uint8_t max_transform_hierarchy_depth_intra;
} BsHevcCodingBlockGeometry;

typedef struct BsHevcColourDescription {
    uint8_t colour_primaries;
    uint8_t transfer_characteristics;
    uint8_t matrix_coefficients;
    uint8_t present;
} BsHevcColourDescription;

typedef struct BsHevcContentLightLevelInfo {
    uint16_t max_content_light_level;
    uint16_t max_pic_average_light_level;
} BsHevcContentLightLevelInfo;

typedef struct BsHevcCpbEntry {
    uint32_t bit_rate_value_minus1;
    uint32_t cpb_size_value_minus1;
    uint32_t cpb_size_du_value_minus1;
    uint32_t bit_rate_du_value_minus1;
    uint8_t cbr_flag;
} BsHevcCpbEntry;

typedef struct BsHevcDerivedShortTermRefPicSet {
    uint32_t references_count;
    struct BsHevcDerivedShortTermReference* references;
    uint32_t num_negative_pics;
    uint32_t num_positive_pics;
} BsHevcDerivedShortTermRefPicSet;

typedef struct BsHevcDerivedShortTermReference {
    int32_t delta_poc;
    uint8_t used_by_curr_pic;
    uint8_t negative;
} BsHevcDerivedShortTermReference;

typedef struct BsHevcDisplayDimensions {
    uint32_t width;
    uint32_t height;
} BsHevcDisplayDimensions;

typedef struct BsHevcFramePackingArrangement {
    uint32_t fp_arrangement_id;
    uint8_t fp_arrangement_cancel_flag;
    uint8_t fp_arrangement_type;
    uint8_t fp_quincunx_sampling_flag;
    uint8_t fp_content_interpretation_type;
    uint8_t fp_spatial_flipping_flag;
    uint8_t fp_frame0_flipped_flag;
    uint8_t fp_field_views_flag;
    uint8_t fp_current_frame_is_frame0_flag;
    uint8_t fp_frame0_self_contained_flag;
    uint8_t fp_frame1_self_contained_flag;
    uint8_t fp_frame0_grid_position_x;
    uint8_t fp_frame0_grid_position_y;
    uint8_t fp_frame1_grid_position_x;
    uint8_t fp_frame1_grid_position_y;
    uint8_t fp_arrangement_reserved_byte;
    uint8_t fp_arrangement_persistence_flag;
    uint8_t fp_upsampled_aspect_ratio_flag;
} BsHevcFramePackingArrangement;

typedef struct BsHevcHrdTimingInfo {
    uint32_t num_units_in_tick;
    uint32_t time_scale;
} BsHevcHrdTimingInfo;

typedef struct BsHevcInterRpsPrediction {
    uint8_t delta_idx_present;
    uint32_t delta_idx_minus1;
    uint32_t reference_rps_idx;
    uint8_t delta_rps_sign;
    uint32_t abs_delta_rps_minus1;
    int32_t delta_rps;
    uint32_t entries_count;
    struct BsHevcInterRpsPredictionEntry* entries;
} BsHevcInterRpsPrediction;

typedef struct BsHevcInterRpsPredictionEntry {
    uint8_t used_by_curr_pic_flag;
    uint8_t use_delta_flag;
} BsHevcInterRpsPredictionEntry;

typedef struct BsHevcLevel {
    uint8_t level_idc;
} BsHevcLevel;

typedef struct BsHevcMasteringDisplayColourVolumeChromaticity {
    uint16_t x;
    uint16_t y;
} BsHevcMasteringDisplayColourVolumeChromaticity;

typedef struct BsHevcPictureStructure {
    uint8_t field_seq;
    uint8_t bottom_field;
} BsHevcPictureStructure;

typedef struct BsHevcPocConfiguration {
    uint8_t log2_max_pic_order_cnt_lsb_minus4;
} BsHevcPocConfiguration;

typedef struct BsHevcPps3dExtension {
    uint8_t dlts_present_flag;
    uint32_t pps_depth_layers_minus1;
    uint32_t pps_bit_depth_for_depth_layers_minus8;
    uint32_t depth_layer_transforms_count;
    struct BsHevcPps3dExtensionDepthLayerTransform* depth_layer_transforms;
} BsHevcPps3dExtension;

typedef struct BsHevcPps3dExtensionDepthLayerTransform {
    uint8_t dlt_flag;
    uint8_t dlt_pred_flag;
    uint8_t dlt_val_flags_present_flag;
    uint32_t dlt_value_flag_count;
    uint8_t* dlt_value_flag;
} BsHevcPps3dExtensionDepthLayerTransform;

typedef struct BsHevcPpsColourMappingOctant {
    uint8_t split_octant_flag;
    uint32_t partition_coded_res_flags_count;
    uint8_t* partition_coded_res_flags;
} BsHevcPpsColourMappingOctant;

typedef struct BsHevcPpsDeblockingFilter {
    uint8_t deblocking_filter_control_present_flag;
    uint8_t deblocking_filter_override_enabled_flag;
    uint8_t pps_deblocking_filter_disabled_flag;
    int32_t pps_beta_offset_div2;
    int32_t pps_tc_offset_div2;
} BsHevcPpsDeblockingFilter;

typedef struct BsHevcPpsExtension {
    uint8_t extension_present_flag;
    uint8_t range_extension_flag;
    uint8_t multilayer_extension_flag;
    uint8_t extension_3d_flag;
    uint8_t scc_extension_flag;
    uint8_t reserved_extension_flags[4];
    uint8_t extension_data_present;
} BsHevcPpsExtension;

typedef struct BsHevcPpsMultilayerExtension {
    uint8_t poc_reset_info_present_flag;
    uint8_t pps_infer_scaling_list_flag;
    uint32_t pps_scaling_list_ref_layer_id;
    uint32_t ref_location_offsets_count;
    struct BsHevcPpsRefLocationOffset* ref_location_offsets;
    uint8_t colour_mapping_enabled_flag;
    uint32_t num_cm_ref_layers_minus1;
    uint32_t cm_ref_layer_id_count;
    uint32_t* cm_ref_layer_id;
    uint32_t cm_octant_depth;
    uint32_t cm_y_part_num_log2;
    uint32_t luma_bit_depth_cm_input_minus8;
    uint32_t chroma_bit_depth_cm_input_minus8;
    uint32_t luma_bit_depth_cm_output_minus8;
    uint32_t chroma_bit_depth_cm_output_minus8;
    uint32_t cm_res_quant_bits;
    uint32_t cm_delta_flc_bits_minus1;
    int32_t cm_adapt_threshold_u_delta;
    int32_t cm_adapt_threshold_v_delta;
    uint32_t colour_mapping_octants_count;
    struct BsHevcPpsColourMappingOctant* colour_mapping_octants;
} BsHevcPpsMultilayerExtension;

typedef struct BsHevcPpsRangeExtension {
    uint32_t log2_max_transform_skip_block_size_minus2;
    uint8_t cross_component_prediction_enabled_flag;
    uint8_t chroma_qp_offset_list_enabled_flag;
    uint32_t diff_cu_chroma_qp_offset_depth;
    uint32_t chroma_qp_offset_list_len_minus1;
    uint32_t cb_qp_offset_list_count;
    int32_t* cb_qp_offset_list;
    uint32_t cr_qp_offset_list_count;
    int32_t* cr_qp_offset_list;
    uint32_t log2_sao_offset_scale_luma;
    uint32_t log2_sao_offset_scale_chroma;
} BsHevcPpsRangeExtension;

typedef struct BsHevcPpsRefLocationOffset {
    uint32_t ref_loc_offset_layer_id;
    uint8_t scaled_ref_layer_offset_present_flag;
    int32_t scaled_ref_layer_left_offset;
    int32_t scaled_ref_layer_top_offset;
    int32_t scaled_ref_layer_right_offset;
    int32_t scaled_ref_layer_bottom_offset;
    uint8_t ref_region_offset_present_flag;
    int32_t ref_region_left_offset;
    int32_t ref_region_top_offset;
    int32_t ref_region_right_offset;
    int32_t ref_region_bottom_offset;
    uint8_t resample_phase_set_present_flag;
    uint32_t phase_hor_luma;
    uint32_t phase_ver_luma;
    uint32_t phase_hor_chroma_plus8;
    uint32_t phase_ver_chroma_plus8;
} BsHevcPpsRefLocationOffset;

typedef struct BsHevcPpsSccExtension {
    uint8_t pps_curr_pic_ref_enabled_flag;
    uint8_t residual_adaptive_colour_transform_enabled_flag;
    uint8_t pps_slice_act_qp_offsets_present_flag;
    int32_t pps_act_y_qp_offset_plus5;
    int32_t pps_act_cb_qp_offset_plus5;
    int32_t pps_act_cr_qp_offset_plus3;
    uint8_t pps_palette_predictor_initializers_present_flag;
    uint32_t pps_num_palette_predictor_initializers;
    uint8_t monochrome_palette_flag;
    uint32_t luma_bit_depth_entry_minus8;
    uint32_t chroma_bit_depth_entry_minus8;
    uint32_t pps_palette_predictor_initializer[3][kMaxPalettePredictorSize];
} BsHevcPpsSccExtension;

typedef struct BsHevcPpsTileConfiguration {
    uint8_t tiles_enabled_flag;
    uint32_t num_tile_columns_minus1;
    uint32_t num_tile_rows_minus1;
    uint8_t uniform_spacing_flag;
    uint32_t column_width_minus1_count;
    uint32_t* column_width_minus1;
    uint32_t row_height_minus1_count;
    uint32_t* row_height_minus1;
    uint8_t loop_filter_across_tiles_enabled_flag;
} BsHevcPpsTileConfiguration;

typedef struct BsHevcPredictionWeight {
    uint8_t luma_weight_luma_flag;
    int32_t delta_luma_weight;
    int32_t luma_offset;
    uint8_t chroma_weight_flag;
    int32_t delta_chroma_weight[2];
    int32_t delta_chroma_offset[2];
} BsHevcPredictionWeight;

typedef struct BsHevcPredictionWeightTable {
    uint32_t luma_log2_weight_denom;
    int32_t delta_chroma_log2_weight_denom;
    uint32_t l0_count;
    struct BsHevcPredictionWeight* l0;
    uint32_t l1_count;
    struct BsHevcPredictionWeight* l1;
} BsHevcPredictionWeightTable;

typedef struct BsHevcProfileTierLevelId {
    int profile_space;
    int tier;
    uint8_t profile_idc;
    uint8_t compatibility_flags[32];
    struct BsHevcLevel level;
} BsHevcProfileTierLevelId;

typedef struct BsHevcProfileTierLevelSubLayer {
    uint8_t profile_space;
    uint8_t tier_flag;
    uint8_t profile_idc;
    uint8_t profile_compatibility_flag[32];
    uint8_t progressive_source_flag;
    uint8_t interlaced_source_flag;
    uint8_t non_packed_constraint_flag;
    uint8_t frame_only_constraint_flag;
    uint64_t reserved_zero_44bits;
    uint8_t level_idc;
} BsHevcProfileTierLevelSubLayer;

typedef struct BsHevcRecoveryPoint {
    int32_t recovery_poc_cnt;
    uint8_t exact_match_flag;
    uint8_t broken_link_flag;
    uint8_t changing_slice_group_idc;
} BsHevcRecoveryPoint;

typedef struct BsHevcRefPicListModification {
    uint8_t modification_flag;
    uint32_t list_entry_count;
    uint32_t* list_entry;
} BsHevcRefPicListModification;

typedef struct BsHevcRefPicListModificationData {
    struct BsHevcRefPicListModification list0;
    struct BsHevcRefPicListModification list1;
} BsHevcRefPicListModificationData;

typedef struct BsHevcReferencePictureSetInfo {
    uint32_t num_negative_pics;
    uint32_t num_positive_pics;
    uint32_t num_delta_pocs;
} BsHevcReferencePictureSetInfo;

typedef struct BsHevcSampleAspectRatio {
    uint16_t width;
    uint16_t height;
} BsHevcSampleAspectRatio;

typedef struct BsHevcSampleAspectRatioTableEntry {
    uint8_t idc;
    uint16_t width;
    uint16_t height;
} BsHevcSampleAspectRatioTableEntry;

typedef struct BsHevcScalingListMatrix {
    uint8_t pred_mode_flag;
    uint32_t pred_matrix_id_delta;
    int32_t dc_coef_minus8;
    int32_t dc_coef;
    uint8_t coefficient_count;
    uint8_t coefficients[kScalingListMaxCoefficients];
} BsHevcScalingListMatrix;

typedef struct BsHevcSeiExtendedValue {
    uint32_t value;
    uint64_t bytes_consumed;
    uint8_t complete;
} BsHevcSeiExtendedValue;

typedef struct BsHevcSeiMessageHeader {
    uint32_t payload_type;
    uint32_t payload_size;
    uint64_t header_size;
} BsHevcSeiMessageHeader;

typedef struct BsHevcShortTermNegativePicture {
    uint32_t delta_poc_minus1;
    uint8_t used_by_curr_pic;
    int32_t delta_poc;
} BsHevcShortTermNegativePicture;

typedef struct BsHevcShortTermPositivePicture {
    uint32_t delta_poc_minus1;
    uint8_t used_by_curr_pic;
    int32_t delta_poc;
} BsHevcShortTermPositivePicture;

typedef struct BsHevcShortTermRefPicSet {
    uint32_t index;
    uint8_t inter_ref_pic_set_prediction_flag;
    uint32_t num_negative_pics;
    uint32_t num_positive_pics;
    uint32_t negative_pics_count;
    struct BsHevcShortTermNegativePicture* negative_pics;
    uint32_t positive_pics_count;
    struct BsHevcShortTermPositivePicture* positive_pics;
    struct BsHevcInterRpsPrediction inter_prediction;
    uint32_t num_delta_pocs;
} BsHevcShortTermRefPicSet;

typedef struct BsHevcSliceDeblockingFilter {
    uint8_t override_flag;
    uint8_t disabled_flag;
    int32_t beta_offset_div2;
    int32_t tc_offset_div2;
} BsHevcSliceDeblockingFilter;

typedef struct BsHevcSliceEntryPointOffsets {
    uint32_t num_entry_point_offsets;
    uint32_t offset_len_minus1;
    uint32_t entry_point_offset_minus1_count;
    uint32_t* entry_point_offset_minus1;
} BsHevcSliceEntryPointOffsets;

typedef struct BsHevcSliceHeaderExtension {
    uint32_t length;
    uint32_t data_count;
    uint8_t* data;
} BsHevcSliceHeaderExtension;

typedef struct BsHevcSliceLongTermReference {
    uint32_t lt_idx_sps;
    uint32_t poc_lsb_lt;
    uint8_t used_by_curr_pic_lt_flag;
    uint8_t delta_poc_msb_present_flag;
    uint32_t delta_poc_msb_cycle_lt;
} BsHevcSliceLongTermReference;

typedef struct BsHevcSliceReferencePictureInfo {
    uint8_t num_ref_idx_active_override_flag;
    uint32_t num_ref_idx_l0_active_minus1;
    uint32_t num_ref_idx_l1_active_minus1;
    struct BsHevcRefPicListModificationData list_modification;
    uint32_t num_poc_total_curr;
} BsHevcSliceReferencePictureInfo;

typedef struct BsHevcSliceSegmentAddress {
    uint32_t value;
    uint32_t bit_width;
} BsHevcSliceSegmentAddress;

typedef struct BsHevcSliceSegmentHeader {
    uint8_t nal_unit_type;
    uint8_t temporal_id;
    uint8_t first_slice_segment_in_pic_flag;
    uint8_t no_output_of_prior_pics_flag;
    uint32_t slice_pic_parameter_set_id;
    uint8_t dependent_slice_segment_flag;
    struct BsHevcSliceSegmentAddress slice_segment_address;
    uint32_t slice_reserved_flag_count;
    uint8_t* slice_reserved_flag;
    int slice_type;
    uint8_t pic_output_flag;
    uint8_t colour_plane_id;
    uint32_t slice_pic_order_cnt_lsb;
    uint8_t short_term_ref_pic_set_sps_flag;
    uint32_t short_term_ref_pic_set_idx;
    struct BsHevcShortTermRefPicSet short_term_ref_pic_set;
    uint32_t num_long_term_sps;
    uint32_t num_long_term_pics;
    uint32_t long_term_references_count;
    struct BsHevcSliceLongTermReference* long_term_references;
    uint8_t slice_temporal_mvp_enabled_flag;
    uint8_t slice_sao_luma_flag;
    uint8_t slice_sao_chroma_flag;
    uint8_t collocated_from_l0_flag;
    uint32_t collocated_ref_idx;
    struct BsHevcSliceReferencePictureInfo reference_pictures;
    uint8_t mvd_l1_zero_flag;
    uint8_t cabac_init_flag;
    uint32_t five_minus_max_num_merge_cand;
    uint8_t prediction_weight_table_present;
    struct BsHevcPredictionWeightTable prediction_weight_table;
    int32_t slice_qp_delta;
    int32_t slice_cb_qp_offset;
    int32_t slice_cr_qp_offset;
    struct BsHevcSliceDeblockingFilter deblocking;
    uint8_t slice_loop_filter_across_slices_enabled_flag;
    struct BsHevcSliceEntryPointOffsets entry_points;
    struct BsHevcSliceHeaderExtension extension;
    int32_t derived_poc;
    uint32_t effective_num_ref_idx_l0;
    uint32_t effective_num_ref_idx_l1;
} BsHevcSliceSegmentHeader;

typedef struct BsHevcSps3dViewExtension {
    uint8_t iv_di_mc_enabled_flag;
    uint8_t iv_mv_scal_enabled_flag;
    uint8_t iv_res_pred_enabled_flag;
    uint8_t depth_ref_enabled_flag;
    uint8_t vsp_mc_enabled_flag;
    uint8_t dbbp_enabled_flag;
    uint8_t tex_mc_enabled_flag;
    uint8_t intra_contour_enabled_flag;
    uint8_t intra_dc_only_wedge_enabled_flag;
    uint8_t cqt_cu_part_pred_enabled_flag;
    uint8_t inter_dc_only_enabled_flag;
    uint8_t skip_intra_enabled_flag;
    uint32_t log2_ivmc_sub_pb_size_minus3;
} BsHevcSps3dViewExtension;

typedef struct BsHevcSpsCodingBlockParameters {
    uint32_t log2_min_luma_coding_block_size_minus3;
    uint32_t log2_diff_max_min_luma_coding_block_size;
    uint32_t log2_min_luma_transform_block_size_minus2;
    uint32_t log2_diff_max_min_luma_transform_block_size;
    uint32_t max_transform_hierarchy_depth_inter;
    uint32_t max_transform_hierarchy_depth_intra;
} BsHevcSpsCodingBlockParameters;

typedef struct BsHevcSpsExtension {
    uint8_t sps_extension_present_flag;
    uint8_t range_extension_flag;
    uint8_t multilayer_extension_flag;
    uint8_t extension_3d_flag;
    uint8_t scc_extension_flag;
    uint8_t reserved_extension_flags[4];
    uint8_t extension_data_present;
} BsHevcSpsExtension;

typedef struct BsHevcSpsGeometry {
    uint32_t coded_width;
    uint32_t coded_height;
    uint32_t display_width;
    uint32_t display_height;
    uint32_t min_cb_size;
    uint32_t max_cb_size;
    uint32_t min_tb_size;
    uint32_t max_tb_size;
} BsHevcSpsGeometry;

typedef struct BsHevcSpsLongTermReferencePictures {
    uint8_t present;
    uint32_t count;
    uint32_t poc_lsb_count;
    uint32_t* poc_lsb;
    uint32_t used_by_curr_pic_count;
    uint8_t* used_by_curr_pic;
} BsHevcSpsLongTermReferencePictures;

typedef struct BsHevcSpsMultilayerExtension {
    uint8_t inter_view_mv_vert_constraint_flag;
} BsHevcSpsMultilayerExtension;

typedef struct BsHevcSpsPcmParameters {
    uint8_t pcm_enabled_flag;
    uint8_t pcm_sample_bit_depth_luma_minus1;
    uint8_t pcm_sample_bit_depth_chroma_minus1;
    uint32_t log2_min_pcm_luma_coding_block_size_minus3;
    uint32_t log2_diff_max_min_pcm_luma_coding_block_size;
    uint8_t pcm_loop_filter_disabled_flag;
} BsHevcSpsPcmParameters;

typedef struct BsHevcSpsRangeExtension {
    uint8_t transform_skip_rotation_enabled_flag;
    uint8_t transform_skip_context_enabled_flag;
    uint8_t implicit_rdpcm_enabled_flag;
    uint8_t explicit_rdpcm_enabled_flag;
    uint8_t extended_precision_processing_flag;
    uint8_t intra_smoothing_disabled_flag;
    uint8_t high_precision_offsets_enabled_flag;
    uint8_t persistent_rice_adaptation_enabled_flag;
    uint8_t cabac_bypass_alignment_enabled_flag;
} BsHevcSpsRangeExtension;

typedef struct BsHevcSpsReferencePictureSetParameters {
    uint32_t num_short_term_ref_pic_sets;
    uint32_t short_term_ref_pic_sets_count;
    struct BsHevcShortTermRefPicSet* short_term_ref_pic_sets;
    uint8_t long_term_ref_pics_present_flag;
    uint32_t num_long_term_ref_pics_sps;
    uint32_t lt_ref_pic_poc_lsb_sps_count;
    uint32_t* lt_ref_pic_poc_lsb_sps;
    uint32_t used_by_curr_pic_lt_sps_flag_count;
    uint8_t* used_by_curr_pic_lt_sps_flag;
} BsHevcSpsReferencePictureSetParameters;

typedef struct BsHevcSpsSccExtension {
    uint8_t sps_curr_pic_ref_enabled_flag;
    uint8_t palette_mode_enabled_flag;
    uint32_t palette_max_size;
    uint32_t delta_palette_max_predictor_size;
    uint8_t sps_palette_predictor_initializers_present_flag;
    uint32_t sps_num_palette_predictor_initializers_minus1;
    uint32_t sps_palette_predictor_initializer[3][kMaxPalettePredictorSize];
    uint32_t motion_vector_resolution_control_idc;
    uint8_t intra_boundary_filtering_disabled_flag;
} BsHevcSpsSccExtension;

typedef struct BsHevcSubLayerHrdParameters {
    uint32_t cpb_entries_count;
    struct BsHevcCpbEntry* cpb_entries;
} BsHevcSubLayerHrdParameters;

typedef struct BsHevcSubLayerOrderingInfo {
    uint32_t max_dec_pic_buffering_minus1;
    uint32_t max_num_reorder_pics;
    uint32_t max_latency_increase_plus1;
} BsHevcSubLayerOrderingInfo;

typedef struct BsHevcTemporalLayer {
    uint8_t id;
    uint8_t profile_present;
    uint8_t level_present;
} BsHevcTemporalLayer;

typedef struct BsHevcTimingInfo {
    uint32_t num_units_in_tick;
    uint32_t time_scale;
    uint8_t poc_proportional_to_timing_flag;
    uint32_t num_ticks_poc_diff_one_minus1;
} BsHevcTimingInfo;

typedef struct BsHevcVideoSignalType {
    uint8_t present;
    uint8_t video_format;
    uint8_t video_full_range_flag;
    struct BsHevcColourDescription colour;
} BsHevcVideoSignalType;

typedef struct BsHevcVpsExtension {
    uint8_t extension_flag;
    uint8_t extension_data_flag;
} BsHevcVpsExtension;

typedef struct BsHevcVpsLayerSet {
    uint32_t layer_id_included_flag_count;
    uint8_t* layer_id_included_flag;
    uint32_t layer_ids_count;
    uint8_t* layer_ids;
} BsHevcVpsLayerSet;

typedef struct BsHevcVpsTimingInfo {
    uint8_t timing_info_present_flag;
    uint32_t num_units_in_tick;
    uint32_t time_scale;
    uint8_t poc_proportional_to_timing_flag;
    uint32_t num_ticks_poc_diff_one_minus1;
    uint32_t num_hrd_parameters;
    uint32_t hrd_parameters_count;
    struct BsHevcVpsHrdParameter* hrd_parameters;
} BsHevcVpsTimingInfo;

typedef struct BsHevcWindow {
    uint32_t left_offset;
    uint32_t right_offset;
    uint32_t top_offset;
    uint32_t bottom_offset;
} BsHevcWindow;

typedef struct BsVp8FrameHeader {
    uint8_t key_frame;
    uint8_t version;
    uint8_t show_frame;
    uint32_t first_part_size;
    uint8_t start_code_ok;
    uint16_t width;
    uint16_t height;
    int32_t presentation_order;
} BsVp8FrameHeader;

typedef struct BsVp9FrameHeader {
    uint8_t frame_marker;
    uint8_t profile;
    uint8_t show_existing_frame;
    uint8_t frame_to_show_map_idx;
    uint8_t show_frame;
    uint8_t error_resilient_mode;
    int frame_type;
    uint8_t intra_only;
    uint32_t width;
    uint32_t height;
    uint8_t frame_size_present;
    uint8_t frame_size_from_refs;
    int32_t presentation_order;
} BsVp9FrameHeader;

typedef struct BsVvcDci {
    uint32_t num_ptls_minus1;
    uint8_t extension_present;
} BsVvcDci;

typedef struct BsVvcOpi {
    uint8_t ols_info_present;
    uint8_t htid_info_present;
    uint32_t ols_idx;
    uint8_t htid_plus1;
    uint8_t extension_present;
} BsVvcOpi;

typedef struct BsVvcPictureHeaderRefPicListsEntry {
    uint8_t inter_layer_ref_pic_flag;
    uint8_t st_ref_pic_flag;
    uint32_t abs_delta_poc_st;
    uint8_t strp_entry_sign_flag;
    uint32_t rpls_poc_lsb_lt;
    uint32_t ilrp_idx;
} BsVvcPictureHeaderRefPicListsEntry;

typedef struct BsVvcPictureHeaderRefPicListsList {
    uint32_t num_ref_entries;
    uint8_t ltrp_in_header_flag;
    uint32_t entries_count;
    struct BsVvcPictureHeaderRefPicListsEntry* entries;
    uint32_t poc_lsb_lt_count;
    uint32_t* poc_lsb_lt;
    uint32_t delta_poc_msb_cycle_present_flag_count;
    uint8_t* delta_poc_msb_cycle_present_flag;
    uint32_t delta_poc_msb_cycle_lt_count;
    uint32_t* delta_poc_msb_cycle_lt;
    uint8_t rpl_sps_flag;
    uint32_t rpl_idx;
} BsVvcPictureHeaderRefPicListsList;

typedef struct BsVvcPictureParameterSet {
    uint8_t pps_id;
    uint8_t sps_id;
    uint8_t mixed_nalu_types_in_pic;
    uint32_t pic_width_in_luma_samples;
    uint32_t pic_height_in_luma_samples;
    uint8_t conformance_window_flag;
    uint32_t conf_win_left_offset;
    uint32_t conf_win_right_offset;
    uint32_t conf_win_top_offset;
    uint32_t conf_win_bottom_offset;
    uint8_t scaling_window_explicit_signalling_flag;
    int32_t scaling_win_left_offset;
    int32_t scaling_win_right_offset;
    int32_t scaling_win_top_offset;
    int32_t scaling_win_bottom_offset;
    uint8_t output_flag_present_flag;
    uint8_t no_pic_partition_flag;
    uint8_t subpic_id_mapping_present_flag;
    uint32_t num_subpics_minus1;
    uint8_t subpic_id_len_minus1;
    uint32_t subpic_id_count;
    uint32_t* subpic_id;
    uint8_t log2_ctu_size_minus5;
    uint32_t num_exp_tile_columns_minus1;
    uint32_t num_exp_tile_rows_minus1;
    uint32_t tile_column_width_minus1_count;
    uint32_t* tile_column_width_minus1;
    uint32_t tile_row_height_minus1_count;
    uint32_t* tile_row_height_minus1;
    uint32_t num_tile_columns;
    uint32_t num_tile_rows;
    uint32_t num_tiles_in_pic;
    uint32_t col_width_val_count;
    uint32_t* col_width_val;
    uint32_t row_height_val_count;
    uint32_t* row_height_val;
    uint8_t loop_filter_across_tiles_enabled_flag;
    uint8_t rect_slice_flag;
    uint8_t single_slice_per_subpic_flag;
    uint32_t num_slices_in_pic_minus1;
    uint8_t tile_idx_delta_present_flag;
    uint32_t slice_width_in_tiles_minus1_count;
    uint32_t* slice_width_in_tiles_minus1;
    uint32_t slice_height_in_tiles_minus1_count;
    uint32_t* slice_height_in_tiles_minus1;
    uint32_t num_exp_slices_in_tile_count;
    uint32_t* num_exp_slices_in_tile;
    uint32_t tile_idx_delta_val_count;
    int32_t* tile_idx_delta_val;
    uint32_t slice_top_left_tile_idx_count;
    uint32_t* slice_top_left_tile_idx;
    uint32_t num_slices_in_tile_count;
    uint32_t* num_slices_in_tile;
    uint32_t slice_height_in_ctus_count;
    uint32_t* slice_height_in_ctus;
    uint8_t loop_filter_across_slices_enabled_flag;
    uint8_t cabac_init_present_flag;
    uint32_t num_ref_idx_default_active_minus1[2];
    uint8_t rpl1_idx_present_flag;
    uint8_t weighted_pred_flag;
    uint8_t weighted_bipred_flag;
    uint8_t ref_wraparound_enabled_flag;
    uint32_t pic_width_minus_wraparound_offset;
    int32_t init_qp_minus26;
    uint8_t cu_qp_delta_enabled_flag;
    uint8_t chroma_tool_offsets_present_flag;
    int32_t cb_qp_offset;
    int32_t cr_qp_offset;
    uint8_t joint_cbcr_qp_offset_present_flag;
    int32_t joint_cbcr_qp_offset_value;
    uint8_t slice_chroma_qp_offsets_present_flag;
    uint8_t cu_chroma_qp_offset_list_enabled_flag;
    uint32_t chroma_qp_offset_list_len_minus1;
    uint32_t cb_qp_offset_list_count;
    int32_t* cb_qp_offset_list;
    uint32_t cr_qp_offset_list_count;
    int32_t* cr_qp_offset_list;
    uint32_t joint_cbcr_qp_offset_list_count;
    int32_t* joint_cbcr_qp_offset_list;
    uint8_t deblocking_filter_control_present_flag;
    uint8_t deblocking_filter_override_enabled_flag;
    uint8_t deblocking_filter_disabled_flag;
    uint8_t dbf_info_in_ph_flag;
    int32_t luma_beta_offset_div2;
    int32_t luma_tc_offset_div2;
    int32_t cb_beta_offset_div2;
    int32_t cb_tc_offset_div2;
    int32_t cr_beta_offset_div2;
    int32_t cr_tc_offset_div2;
    uint8_t rpl_info_in_ph_flag;
    uint8_t sao_info_in_ph_flag;
    uint8_t alf_info_in_ph_flag;
    uint8_t wp_info_in_ph_flag;
    uint8_t qp_delta_info_in_ph_flag;
    uint8_t picture_header_extension_present_flag;
    uint8_t slice_header_extension_present_flag;
    uint8_t extension_flag;
} BsVvcPictureParameterSet;

typedef struct BsVvcSequenceParameterSet {
    uint8_t sps_id;
    uint8_t vps_id;
    uint8_t max_sublayers_minus1;
    uint8_t chroma_format_idc;
    uint8_t log2_ctu_size_minus5;
    uint8_t ptl_dpb_hrd_params_present;
    uint8_t gdr_enabled_flag;
    uint8_t ref_pic_resampling_enabled_flag;
    uint8_t subpic_info_present_flag;
    uint8_t subpic_id_len_minus1;
    uint8_t num_extra_sh_bits;
    uint8_t log2_max_pic_order_cnt_lsb_minus4;
    uint8_t poc_msb_cycle_flag;
    uint8_t poc_msb_cycle_len_minus1;
    uint8_t num_extra_ph_bits;
    uint8_t res_change_in_clvs_allowed_flag;
    uint32_t pic_width_max_in_luma_samples;
    uint32_t pic_height_max_in_luma_samples;
    uint8_t conformance_window_flag;
    uint32_t conf_win_left_offset;
    uint32_t conf_win_right_offset;
    uint32_t conf_win_top_offset;
    uint32_t conf_win_bottom_offset;
    uint32_t num_subpics_minus1;
    uint8_t independent_subpics_flag;
    uint8_t subpic_same_size_flag;
    uint8_t subpic_id_mapping_explicitly_signalled_flag;
    uint8_t subpic_id_mapping_present_flag;
    uint8_t bitdepth_minus8;
    uint8_t entropy_coding_sync_enabled_flag;
    uint8_t entry_point_offsets_present_flag;
    uint8_t num_extra_ph_bytes;
    uint8_t num_extra_sh_bytes;
    uint8_t sublayer_dpb_params_flag;
    uint32_t log2_min_luma_coding_block_size_minus2;
    uint8_t partition_constraints_override_enabled_flag;
    uint32_t log2_diff_min_qt_min_cb_intra_slice_luma;
    uint32_t max_mtt_hierarchy_depth_intra_slice_luma;
    uint32_t log2_diff_max_bt_min_qt_intra_slice_luma;
    uint32_t log2_diff_max_tt_min_qt_intra_slice_luma;
    uint8_t qtbtt_dual_tree_intra_flag;
    uint32_t log2_diff_min_qt_min_cb_intra_slice_chroma;
    uint32_t max_mtt_hierarchy_depth_intra_slice_chroma;
    uint32_t log2_diff_max_bt_min_qt_intra_slice_chroma;
    uint32_t log2_diff_max_tt_min_qt_intra_slice_chroma;
    uint32_t log2_diff_min_qt_min_cb_inter_slice;
    uint32_t max_mtt_hierarchy_depth_inter_slice;
    uint32_t log2_diff_max_bt_min_qt_inter_slice;
    uint32_t log2_diff_max_tt_min_qt_inter_slice;
    uint8_t max_luma_transform_size_64_flag;
    uint8_t transform_skip_enabled_flag;
    uint32_t log2_transform_skip_max_size_minus2;
    uint8_t bdpcm_enabled_flag;
    uint8_t mts_enabled_flag;
    uint8_t explicit_mts_intra_enabled_flag;
    uint8_t explicit_mts_inter_enabled_flag;
    uint8_t lfnst_enabled_flag;
    uint8_t joint_cbcr_enabled_flag;
    uint8_t same_qp_table_for_chroma_flag;
    uint8_t sao_enabled_flag;
    uint8_t alf_enabled_flag;
    uint8_t ccalf_enabled_flag;
    uint8_t lmcs_enabled_flag;
    uint8_t weighted_pred_flag;
    uint8_t weighted_bipred_flag;
    uint8_t long_term_ref_pics_flag;
    uint8_t inter_layer_prediction_enabled_flag;
    uint8_t idr_rpl_present_flag;
    uint8_t rpl1_same_as_rpl0_flag;
    uint32_t num_ref_pic_lists[2];
    uint8_t ref_wraparound_enabled_flag;
    uint8_t temporal_mvp_enabled_flag;
    uint8_t sbtmvp_enabled_flag;
    uint8_t amvr_enabled_flag;
    uint8_t bdof_enabled_flag;
    uint8_t bdof_control_present_in_ph_flag;
    uint8_t smvd_enabled_flag;
    uint8_t dmvr_enabled_flag;
    uint8_t dmvr_control_present_in_ph_flag;
    uint8_t mmvd_enabled_flag;
    uint8_t mmvd_fullpel_only_enabled_flag;
    uint32_t six_minus_max_num_merge_cand;
    uint8_t sbt_enabled_flag;
    uint8_t affine_enabled_flag;
    uint32_t five_minus_max_num_subblock_merge_cand;
    uint8_t six_param_affine_enabled_flag;
    uint8_t affine_amvr_enabled_flag;
    uint8_t affine_prof_enabled_flag;
    uint8_t prof_control_present_in_ph_flag;
    uint8_t bcw_enabled_flag;
    uint8_t ciip_enabled_flag;
    uint8_t gpm_enabled_flag;
    uint32_t max_num_merge_cand_minus_max_num_gpm_cand;
    uint32_t log2_parallel_merge_level_minus2;
    uint8_t isp_enabled_flag;
    uint8_t mrl_enabled_flag;
    uint8_t mip_enabled_flag;
    uint8_t cclm_enabled_flag;
    uint8_t chroma_horizontal_collocated_flag;
    uint8_t chroma_vertical_collocated_flag;
    uint8_t palette_enabled_flag;
    uint8_t act_enabled_flag;
    uint32_t min_qp_prime_ts_minus4;
    uint8_t ibc_enabled_flag;
    uint32_t six_minus_max_num_ibc_merge_cand;
    uint8_t ladf_enabled_flag;
    uint32_t num_ladf_intervals_minus2;
    int32_t ladf_lowest_interval_qp_offset;
    uint8_t explicit_scaling_list_enabled_flag;
    uint8_t scaling_matrix_for_lfnst_disabled_flag;
    uint8_t scaling_matrix_for_alternative_colour_space_disabled_flag;
    uint8_t scaling_matrix_designated_colour_space_flag;
    uint8_t scaling_enabled_flag;
    uint8_t dep_quant_enabled_flag;
    uint8_t sign_data_hiding_enabled_flag;
    uint8_t virtual_boundaries_enabled_flag;
    uint8_t virtual_boundaries_present_flag;
    uint32_t num_ver_virtual_boundaries;
    uint32_t num_hor_virtual_boundaries;
    uint32_t virtual_boundary_pos_x_minus1_count;
    uint32_t* virtual_boundary_pos_x_minus1;
    uint32_t virtual_boundary_pos_y_minus1_count;
    uint32_t* virtual_boundary_pos_y_minus1;
    uint8_t timing_hrd_params_present_flag;
    uint8_t sublayer_cpb_params_present_flag;
    uint8_t general_nal_hrd_params_present_flag;
    uint8_t general_vcl_hrd_params_present_flag;
    uint8_t general_same_pic_timing_in_all_ols_flag;
    uint8_t general_du_hrd_params_present_flag;
    uint8_t bit_rate_scale;
    uint8_t cpb_size_scale;
    uint8_t cpb_size_du_scale;
    uint32_t hrd_cpb_cnt_minus1;
    uint8_t tick_divisor_minus2;
    uint8_t field_seq_flag;
    uint8_t vui_parameters_present_flag;
    uint32_t vui_payload_size_minus1;
    uint8_t extension_flag;
    uint8_t range_extension_flag;
    uint8_t extension_7bits;
    uint8_t extended_precision_flag;
    uint8_t ts_residual_coding_rice_present_in_sh_flag;
    uint8_t rrc_rice_extension_flag;
    uint8_t persistent_rice_adaptation_enabled_flag;
    uint8_t reverse_last_sig_coeff_enabled_flag;
} BsVvcSequenceParameterSet;

typedef struct BsVvcSequenceParameterSetRefPicListEntry {
    uint8_t inter_layer_ref_pic_flag;
    uint8_t st_ref_pic_flag;
    uint32_t abs_delta_poc_st;
    uint8_t strp_entry_sign_flag;
    uint32_t rpls_poc_lsb_lt;
    uint32_t ilrp_idx;
} BsVvcSequenceParameterSetRefPicListEntry;

typedef struct BsVvcSequenceParameterSetRefPicListStruct {
    uint32_t num_ref_entries;
    uint8_t ltrp_in_header_flag;
    uint32_t entries_count;
    struct BsVvcSequenceParameterSetRefPicListEntry* entries;
} BsVvcSequenceParameterSetRefPicListStruct;

typedef struct BsVvcVideoParameterSet {
    uint8_t vps_id;
    uint8_t max_layers_minus1;
    uint8_t max_sublayers_minus1;
    uint8_t default_ptl_dpb_hrd_max_tid_flag;
    uint8_t all_independent_layers;
    uint32_t layer_ids_count;
    uint8_t* layer_ids;
    uint32_t independent_layer_flag_count;
    uint8_t* independent_layer_flag;
    uint8_t each_layer_is_an_ols_flag;
    uint8_t ols_mode_idc;
    uint8_t num_output_layer_sets_minus2;
    uint8_t num_ptls_minus1;
    uint32_t pt_present_flag_count;
    uint8_t* pt_present_flag;
    uint32_t ptl_max_tid_count;
    uint8_t* ptl_max_tid;
    uint32_t ols_ptl_idx_count;
    uint8_t* ols_ptl_idx;
    uint8_t extension_flag;
} BsVvcVideoParameterSet;

typedef struct BsAv1SequenceHeader {
    uint8_t seq_profile;
    uint8_t still_picture;
    uint8_t reduced_still_picture_header;
    uint8_t timing_info_present_flag;
    struct BsAv1TimingInfo timing_info;
    uint8_t decoder_model_info_present_flag;
    struct BsAv1DecoderModelInfo decoder_model_info;
    uint8_t initial_display_delay_present_flag;
    uint8_t operating_points_cnt_minus_1;
    uint16_t operating_point_idc[32];
    uint8_t seq_level_idx[32];
    uint8_t seq_tier[32];
    uint8_t decoder_model_present_for_this_op[32];
    uint32_t decoder_buffer_delay[32];
    uint32_t encoder_buffer_delay[32];
    uint8_t low_delay_mode_flag[32];
    uint8_t initial_display_delay_present_for_this_op[32];
    uint8_t initial_display_delay_minus_1[32];
    uint8_t frame_width_bits_minus_1;
    uint8_t frame_height_bits_minus_1;
    uint32_t max_frame_width;
    uint32_t max_frame_height;
    uint8_t dimensions_present;
    uint8_t frame_id_numbers_present_flag;
    uint8_t delta_frame_id_length_minus_2;
    uint8_t additional_frame_id_length_minus_1;
    uint8_t use_128x128_superblock;
    uint8_t enable_filter_intra;
    uint8_t enable_intra_edge_filter;
    uint8_t enable_interintra_compound;
    uint8_t enable_masked_compound;
    uint8_t enable_warped_motion;
    uint8_t enable_dual_filter;
    uint8_t enable_order_hint;
    uint8_t enable_jnt_comp;
    uint8_t enable_ref_frame_mvs;
    uint8_t order_hint_bits_minus_1;
    uint8_t seq_choose_screen_content_tools;
    uint8_t seq_force_screen_content_tools;
    uint8_t seq_choose_integer_mv;
    uint8_t seq_force_integer_mv;
    uint8_t enable_superres;
    uint8_t enable_cdef;
    uint8_t enable_restoration;
    struct BsAv1ColorConfig color_config;
    uint8_t film_grain_params_present;
    uint8_t seq_level_idx_0;
    uint8_t seq_tier_0;
    uint8_t equal_picture_interval;
    uint8_t buffer_delay_length_minus_1;
    uint8_t buffer_removal_time_length_minus_1;
    uint8_t frame_presentation_time_length_minus_1;
} BsAv1SequenceHeader;

typedef struct BsAvcPictureParameterSet {
    uint8_t pic_parameter_set_id;
    uint8_t seq_parameter_set_id;
    uint8_t entropy_coding_mode_flag;
    uint8_t bottom_field_pic_order_in_frame_present_flag;
    uint8_t num_slice_groups_minus1;
    struct BsAvcSliceGroupMap slice_group_map;
    uint8_t num_ref_idx_l0_default_active_minus1;
    uint8_t num_ref_idx_l1_default_active_minus1;
    uint8_t weighted_pred_flag;
    uint8_t weighted_bipred_idc;
    int32_t pic_init_qp_minus26;
    int32_t pic_init_qs_minus26;
    int32_t chroma_qp_index_offset;
    uint8_t deblocking_filter_control_present_flag;
    uint8_t constrained_intra_pred_flag;
    uint8_t redundant_pic_cnt_present_flag;
    uint8_t transform_8x8_mode_flag;
    uint8_t pic_scaling_matrix_present_flag;
    struct BsAvcScalingList pic_scaling_lists;
    int32_t second_chroma_qp_index_offset;
} BsAvcPictureParameterSet;

typedef struct BsAvcSequenceParameterSet {
    uint8_t profile_idc;
    uint8_t constraint_set_flag[6];
    uint8_t level_idc;
    uint8_t seq_parameter_set_id;
    uint8_t chroma_format_idc;
    uint8_t separate_colour_plane_flag;
    uint8_t bit_depth_luma_minus8;
    uint8_t bit_depth_chroma_minus8;
    uint8_t qpprime_y_zero_transform_bypass_flag;
    struct BsAvcScalingList scaling_lists;
    uint8_t log2_max_frame_num_minus4;
    uint8_t pic_order_cnt_type;
    uint8_t log2_max_pic_order_cnt_lsb_minus4;
    uint8_t delta_pic_order_always_zero_flag;
    int32_t offset_for_non_ref_pic;
    int32_t offset_for_top_to_bottom_field;
    uint8_t num_ref_frames_in_pic_order_cnt_cycle;
    int32_t offset_for_ref_frame[255];
    uint8_t max_num_ref_frames;
    uint8_t gaps_in_frame_num_value_allowed_flag;
    uint32_t pic_width_in_mbs_minus1;
    uint32_t pic_height_in_map_units_minus1;
    uint8_t frame_mbs_only_flag;
    uint8_t mb_adaptive_frame_field_flag;
    uint8_t direct_8x8_inference_flag;
    uint8_t frame_cropping_flag;
    uint32_t frame_crop_left_offset;
    uint32_t frame_crop_right_offset;
    uint32_t frame_crop_top_offset;
    uint32_t frame_crop_bottom_offset;
    uint8_t vui_parameters_present_flag;
    struct BsAvcVuiParameters vui;
} BsAvcSequenceParameterSet;

typedef struct BsHevcHrdCommonInfo {
    uint8_t timing_info_present_flag;
    struct BsHevcHrdTimingInfo timing;
    uint8_t nal_hrd_parameters_present_flag;
    uint8_t vcl_hrd_parameters_present_flag;
    uint8_t sub_pic_hrd_params_present_flag;
    uint8_t tick_divisor_minus2;
    uint8_t du_cpb_removal_delay_increment_length_minus1;
    uint8_t sub_pic_cpb_params_in_pic_timing_sei_flag;
    uint8_t dpb_output_delay_du_length_minus1;
    uint8_t bit_rate_scale;
    uint8_t cpb_size_scale;
    uint8_t cpb_size_du_scale;
    uint8_t initial_cpb_removal_delay_length_minus1;
    uint8_t au_cpb_removal_delay_length_minus1;
    uint8_t dpb_output_delay_length_minus1;
} BsHevcHrdCommonInfo;

typedef struct BsHevcHrdSubLayer {
    uint8_t fixed_pic_rate_general_flag;
    uint8_t fixed_pic_rate_within_cvs_flag;
    uint32_t elemental_duration_in_tc_minus1;
    uint8_t low_delay_hrd_flag;
    uint8_t cpb_cnt_minus1;
    struct BsHevcSubLayerHrdParameters nal;
    struct BsHevcSubLayerHrdParameters vcl;
} BsHevcHrdSubLayer;

typedef struct BsHevcMasteringDisplayColourVolume {
    struct BsHevcMasteringDisplayColourVolumeChromaticity display_primaries[3];
    struct BsHevcMasteringDisplayColourVolumeChromaticity white_point;
    uint32_t max_display_mastering_luminance;
    uint32_t min_display_mastering_luminance;
} BsHevcMasteringDisplayColourVolume;

typedef struct BsHevcPictureDimensions {
    uint32_t width_luma_samples;
    uint32_t height_luma_samples;
    struct BsHevcWindow conformance_window;
    uint8_t conformance_window_flag;
} BsHevcPictureDimensions;

typedef struct BsHevcProfileTierLevel {
    uint8_t max_sub_layers_minus1;
    uint8_t general_profile_space;
    uint8_t general_tier_flag;
    uint8_t general_profile_idc;
    uint8_t general_profile_compatibility_flag[32];
    uint8_t general_progressive_source_flag;
    uint8_t general_interlaced_source_flag;
    uint8_t general_non_packed_constraint_flag;
    uint8_t general_frame_only_constraint_flag;
    uint64_t general_reserved_zero_44bits;
    uint8_t general_level_idc;
    uint8_t sub_layer_profile_present_flag[8];
    uint8_t sub_layer_level_present_flag[8];
    struct BsHevcProfileTierLevelSubLayer sub_layer[8];
} BsHevcProfileTierLevel;

typedef struct BsHevcScalingListData {
    struct BsHevcScalingListMatrix matrices[kScalingListSizeIds][kScalingListMatrixIds];
} BsHevcScalingListData;

typedef struct BsHevcSps3dExtension {
    struct BsHevcSps3dViewExtension views[2];
} BsHevcSps3dExtension;

typedef struct BsHevcVideoParameterSet {
    uint8_t vps_video_parameter_set_id;
    uint8_t vps_base_layer_internal_flag;
    uint8_t vps_base_layer_available_flag;
    uint8_t vps_max_layers_minus1;
    uint8_t vps_max_sub_layers_minus1;
    uint8_t vps_temporal_id_nesting_flag;
    uint16_t vps_reserved_0xffff_16bits;
    struct BsHevcProfileTierLevel profile_tier_level;
    uint8_t vps_sub_layer_ordering_info_present_flag;
    struct BsHevcSubLayerOrderingInfo sub_layer_ordering_info[8];
    uint8_t vps_max_layer_id;
    uint32_t vps_num_layer_sets_minus1;
    uint32_t layer_sets_count;
    struct BsHevcVpsLayerSet* layer_sets;
    struct BsHevcVpsTimingInfo timing;
    struct BsHevcVpsExtension extension;
} BsHevcVideoParameterSet;

typedef struct BsVvcPictureHeaderRefPicLists {
    struct BsVvcPictureHeaderRefPicListsList rpl[2];
} BsVvcPictureHeaderRefPicLists;

typedef struct BsHevcHrdParameters {
    uint8_t common_info_present;
    struct BsHevcHrdCommonInfo common;
    struct BsHevcHrdSubLayer sub_layers[8];
    uint8_t max_num_sub_layers_minus1;
} BsHevcHrdParameters;

typedef struct BsHevcPpsScalingListConfiguration {
    uint8_t scaling_list_data_present_flag;
    struct BsHevcScalingListData scaling_list;
} BsHevcPpsScalingListConfiguration;

typedef struct BsHevcVpsHrdParameter {
    uint32_t layer_set_idx_for_ols_minus1;
    uint8_t common_inf_present_flag;
    struct BsHevcHrdParameters hrd;
} BsHevcVpsHrdParameter;

typedef struct BsHevcVuiParameters {
    uint8_t progressive_source_flag;
    uint8_t interlaced_source_flag;
    uint8_t non_packed_constraint_flag;
    uint8_t non_projected_constraint_flag;
    uint8_t aspect_ratio_info_present_flag;
    struct BsHevcAspectRatio aspect_ratio;
    uint8_t overscan_info_present_flag;
    uint8_t overscan_appropriate_flag;
    struct BsHevcVideoSignalType video_signal;
    struct BsHevcChromaLocationInfo chroma_location;
    uint8_t neutral_chroma_indication_flag;
    uint8_t field_seq_flag;
    uint8_t frame_field_info_present_flag;
    uint8_t default_display_window_flag;
    struct BsHevcWindow default_display_window;
    uint8_t vui_timing_info_present_flag;
    struct BsHevcTimingInfo timing;
    uint8_t hrd_parameters_present_flag;
    struct BsHevcHrdParameters hrd;
    uint8_t bitstream_restriction_flag;
    uint8_t motion_vectors_over_pic_boundaries_flag;
    uint8_t restricted_ref_pic_lists_flag;
    uint32_t min_spatial_segmentation_idc;
    uint32_t max_bytes_per_pic_denom;
    uint32_t max_bits_per_min_cu_denom;
    uint32_t log2_max_mv_length_horizontal;
    uint32_t log2_max_mv_length_vertical;
} BsHevcVuiParameters;

typedef struct BsVvcPictureHeader {
    uint8_t pps_id;
    uint8_t gdr_or_irap_pic_flag;
    uint8_t non_ref_pic_flag;
    uint8_t gdr_pic_flag;
    uint8_t inter_slice_allowed_flag;
    uint8_t intra_slice_allowed_flag;
    uint32_t poc_lsb;
    uint32_t poc_lsb_bits;
    uint32_t recovery_poc_cnt;
    uint8_t poc_msb_cycle_present_flag;
    uint32_t poc_msb_cycle_val;
    uint32_t extra_bits_count;
    uint8_t* extra_bits;
    uint8_t alf_enabled_flag;
    uint8_t num_alf_aps_ids_luma;
    uint32_t alf_aps_id_luma_count;
    uint8_t* alf_aps_id_luma;
    uint8_t alf_cb_enabled_flag;
    uint8_t alf_cr_enabled_flag;
    uint8_t alf_aps_id_chroma;
    uint8_t alf_cc_cb_enabled_flag;
    uint8_t alf_cc_cb_aps_id;
    uint8_t alf_cc_cr_enabled_flag;
    uint8_t alf_cc_cr_aps_id;
    uint8_t lmcs_enabled_flag;
    uint8_t lmcs_aps_id;
    uint8_t chroma_residual_scale_flag;
    uint8_t explicit_scaling_list_enabled_flag;
    uint8_t scaling_list_aps_id;
    uint8_t virtual_boundaries_present_flag;
    uint32_t num_ver_virtual_boundaries;
    uint32_t virtual_boundary_pos_x_minus1_count;
    uint32_t* virtual_boundary_pos_x_minus1;
    uint32_t num_hor_virtual_boundaries;
    uint32_t virtual_boundary_pos_y_minus1_count;
    uint32_t* virtual_boundary_pos_y_minus1;
    uint8_t pic_output_flag;
    struct BsVvcPictureHeaderRefPicLists ref_pic_lists;
    uint8_t partition_constraints_override_flag;
    uint32_t log2_diff_min_qt_min_cb_intra_slice_luma;
    uint32_t max_mtt_hierarchy_depth_intra_slice_luma;
    uint32_t log2_diff_max_bt_min_qt_intra_slice_luma;
    uint32_t log2_diff_max_tt_min_qt_intra_slice_luma;
    uint32_t log2_diff_min_qt_min_cb_intra_slice_chroma;
    uint32_t max_mtt_hierarchy_depth_intra_slice_chroma;
    uint32_t log2_diff_max_bt_min_qt_intra_slice_chroma;
    uint32_t log2_diff_max_tt_min_qt_intra_slice_chroma;
    uint32_t log2_diff_min_qt_min_cb_inter_slice;
    uint32_t max_mtt_hierarchy_depth_inter_slice;
    uint32_t log2_diff_max_bt_min_qt_inter_slice;
    uint32_t log2_diff_max_tt_min_qt_inter_slice;
    uint32_t cu_qp_delta_subdiv_intra_slice;
    uint32_t cu_chroma_qp_offset_subdiv_intra_slice;
    uint32_t cu_qp_delta_subdiv_inter_slice;
    uint32_t cu_chroma_qp_offset_subdiv_inter_slice;
    uint8_t temporal_mvp_enabled_flag;
    uint8_t collocated_from_l0_flag;
    uint32_t collocated_ref_idx;
    uint8_t mmvd_fullpel_only_flag;
    uint8_t mvd_l1_zero_flag;
    uint8_t bdof_disabled_flag;
    uint8_t dmvr_disabled_flag;
    uint8_t prof_disabled_flag;
    int32_t qp_delta;
    uint8_t joint_cbcr_sign_flag;
    uint8_t sao_luma_enabled_flag;
    uint8_t sao_chroma_enabled_flag;
    uint8_t deblocking_params_present_flag;
    uint8_t deblocking_filter_disabled_flag;
    int32_t luma_beta_offset_div2;
    int32_t luma_tc_offset_div2;
    int32_t cb_beta_offset_div2;
    int32_t cb_tc_offset_div2;
    int32_t cr_beta_offset_div2;
    int32_t cr_tc_offset_div2;
    uint32_t extension_length;
    uint32_t extension_data_count;
    uint8_t* extension_data;
    int32_t derived_poc;
} BsVvcPictureHeader;

typedef struct BsVvcSliceHeader {
    uint8_t pps_id;
    uint8_t first_slice_segment_in_pic;
    uint8_t independent_slice_segment;
    uint32_t slice_segment_address;
    uint32_t slice_address;
    int slice_type;
    uint8_t picture_header_in_slice_header_flag;
    struct BsVvcPictureHeader ph;
    uint32_t subpic_id;
    uint32_t curr_subpic_idx;
    uint32_t num_tiles_in_slice_minus1;
    uint32_t extra_bits_count;
    uint8_t* extra_bits;
    uint8_t no_output_of_prior_pics_flag;
    uint8_t alf_enabled_flag;
    uint8_t num_alf_aps_ids_luma;
    uint32_t alf_aps_id_luma_count;
    uint8_t* alf_aps_id_luma;
    uint8_t alf_cb_enabled_flag;
    uint8_t alf_cr_enabled_flag;
    uint8_t alf_aps_id_chroma;
    uint8_t alf_cc_cb_enabled_flag;
    uint8_t alf_cc_cb_aps_id;
    uint8_t alf_cc_cr_enabled_flag;
    uint8_t alf_cc_cr_aps_id;
    uint8_t lmcs_used_flag;
    uint8_t explicit_scaling_list_used_flag;
    struct BsVvcPictureHeaderRefPicLists ref_pic_lists;
    uint8_t num_ref_idx_active_override_flag;
    uint32_t num_ref_idx_active_minus1[2];
    uint32_t num_ref_idx_active[2];
    uint8_t cabac_init_flag;
    uint8_t collocated_from_l0_flag;
    uint32_t collocated_ref_idx;
    int32_t qp_delta;
    int32_t cb_qp_offset;
    int32_t cr_qp_offset;
    int32_t joint_cbcr_qp_offset;
    uint8_t cu_chroma_qp_offset_enabled_flag;
    uint8_t sao_luma_used_flag;
    uint8_t sao_chroma_used_flag;
    uint8_t deblocking_params_present_flag;
    uint8_t deblocking_filter_disabled_flag;
    int32_t luma_beta_offset_div2;
    int32_t luma_tc_offset_div2;
    int32_t cb_beta_offset_div2;
    int32_t cb_tc_offset_div2;
    int32_t cr_beta_offset_div2;
    int32_t cr_tc_offset_div2;
    uint8_t dep_quant_used_flag;
    uint8_t sign_data_hiding_used_flag;
    uint8_t ts_residual_coding_disabled_flag;
    uint32_t ts_residual_coding_rice_idx_minus1;
    uint8_t reverse_last_sig_coeff_flag;
    uint32_t slice_header_extension_length;
    uint32_t slice_header_extension_data_count;
    uint8_t* slice_header_extension_data;
    uint32_t num_entry_points;
    uint32_t entry_offset_len_minus1;
    uint32_t entry_point_offset_minus1_count;
    uint32_t* entry_point_offset_minus1;
    int32_t derived_poc;
} BsVvcSliceHeader;

typedef struct BsHevcPictureParameterSet {
    uint32_t pps_pic_parameter_set_id;
    uint32_t pps_seq_parameter_set_id;
    uint8_t dependent_slice_segments_enabled_flag;
    uint8_t output_flag_present_flag;
    uint8_t num_extra_slice_header_bits;
    uint8_t sign_data_hiding_enabled_flag;
    uint8_t cabac_init_present_flag;
    uint32_t num_ref_idx_l0_default_active_minus1;
    uint32_t num_ref_idx_l1_default_active_minus1;
    int32_t init_qp_minus26;
    int32_t pps_cb_qp_offset;
    int32_t pps_cr_qp_offset;
    uint8_t constrained_intra_pred_flag;
    uint8_t transform_skip_enabled_flag;
    uint8_t cu_qp_delta_enabled_flag;
    uint32_t diff_cu_qp_delta_depth;
    uint8_t slice_chroma_qp_offsets_present_flag;
    uint8_t weighted_pred_flag;
    uint8_t weighted_bipred_flag;
    uint8_t transquant_bypass_enabled_flag;
    struct BsHevcPpsTileConfiguration tiles;
    uint8_t entropy_coding_sync_enabled_flag;
    uint8_t pps_loop_filter_across_slices_enabled_flag;
    struct BsHevcPpsDeblockingFilter deblocking;
    struct BsHevcPpsScalingListConfiguration scaling_list_configuration;
    uint8_t lists_modification_present_flag;
    uint32_t log2_parallel_merge_level_minus2;
    uint8_t slice_segment_header_extension_present_flag;
    struct BsHevcPpsExtension extension;
    struct BsHevcPpsRangeExtension range_extension;
    struct BsHevcPpsSccExtension scc_extension;
    struct BsHevcPpsMultilayerExtension multilayer_extension;
    struct BsHevcPps3dExtension three_d_extension;
} BsHevcPictureParameterSet;

typedef struct BsHevcSequenceParameterSet {
    uint8_t sps_video_parameter_set_id;
    uint8_t sps_max_sub_layers_minus1;
    uint8_t sps_temporal_id_nesting_flag;
    struct BsHevcProfileTierLevel profile_tier_level;
    uint32_t sps_seq_parameter_set_id;
    int chroma_format;
    uint8_t separate_colour_plane_flag;
    uint32_t pic_width_in_luma_samples;
    uint32_t pic_height_in_luma_samples;
    uint8_t conformance_window_flag;
    struct BsHevcWindow conformance_window;
    uint32_t bit_depth_luma_minus8;
    uint32_t bit_depth_chroma_minus8;
    struct BsHevcBitDepth bit_depth;
    uint32_t log2_max_pic_order_cnt_lsb_minus4;
    uint8_t sps_sub_layer_ordering_info_present_flag;
    struct BsHevcSubLayerOrderingInfo sub_layer_ordering_info[8];
    struct BsHevcSpsCodingBlockParameters coding_blocks;
    uint8_t scaling_list_enabled_flag;
    uint8_t sps_scaling_list_data_present_flag;
    struct BsHevcScalingListData scaling_list;
    uint8_t amp_enabled_flag;
    uint8_t sample_adaptive_offset_enabled_flag;
    struct BsHevcSpsPcmParameters pcm;
    struct BsHevcSpsReferencePictureSetParameters reference_picture_sets;
    uint8_t sps_temporal_mvp_enabled_flag;
    uint8_t strong_intra_smoothing_enabled_flag;
    uint8_t vui_parameters_present_flag;
    struct BsHevcVuiParameters vui;
    struct BsHevcSpsExtension extension;
    struct BsHevcSpsRangeExtension range_extension;
    struct BsHevcSpsMultilayerExtension multilayer_extension;
    struct BsHevcSps3dExtension three_d_extension;
    struct BsHevcSpsSccExtension scc_extension;
    struct BsHevcSpsGeometry geometry;
} BsHevcSequenceParameterSet;

#ifdef __cplusplus
}
#endif

#endif /* BS_STRUCTS_H */
